type: object
required:
  - id
  - fullName
  - email
properties:
  id:
    type: string
    format: uuid
    example: 123e4567-e89b-12d3-a456-426614174000
  fullName:
    type: string
    example: John Doe
  email:
    type: string
    format: email
    example: john.doe@example.com
  bio:
    type: string
    example: Experienced strength trainer
  phoneNumber:
    type: string
    example: "+1234567890"
  specialization:
    type: string
    example: Powerlifting
  instagramHandle:
    type: string
    example: "@coachjohn"
  profilePictureUrl:
    type: string
    format: uri
    example: "https://example.com/profile.jpg"
